name       : python-smmap2
version    : 2.0.5
release    : 2
source     :
    - https://files.pythonhosted.org/packages/3b/ba/e49102b3e8ffff644edded25394b2d22ebe3e645f3f6a8139129c4842ffe/smmap2-2.0.5.tar.gz : 29a9ffa0497e7f2be94ca0ed1ca1aa3cd4cf25a1f6b4f5f87f74b46ed91d609a
license    : BSD-3-Clause
component  : programming.python
summary    : A pure python implementation of a sliding window memory map manager
description: |
    A pure python implementation of a sliding window memory map manager
builddeps  :
    - python-nosexcover
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
